/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.Gravador;
import Classes.Musicas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 20241114010045
 */
public class TelaSoundsy extends javax.swing.JFrame {
    
    //Criação de um objeto do tipo arraylist para os usuarios
    ArrayList<Musicas> listaMusicas =  new ArrayList<>();

    /**
     * Creates new form TelaSoub
     */
    public TelaSoundsy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNome = new javax.swing.JTextField();
        tfArtista = new javax.swing.JTextField();
        tfGenero = new javax.swing.JTextField();
        tfDuracao = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();
        jNome = new javax.swing.JLabel();
        jArtista = new javax.swing.JLabel();
        jAlbum = new javax.swing.JLabel();
        jDuracao = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbMusicas = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tfArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfArtistaActionPerformed(evt);
            }
        });

        tfGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGeneroActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Cadastre Suas Músicas");

        jNome.setText("Nome:");

        jArtista.setText("Artista:");

        jAlbum.setText("Gênero:");

        jDuracao.setText("Duração");

        btnLimpar.setText("Limpar");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jButton1.setText("Tabela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabela(evt);
            }
        });

        TbMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Música", "Artista", "Gênero", "Duração"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbMusicas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbMusicasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbMusicas);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addComponent(jNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfArtista)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(123, 123, 123))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jNome)
                            .addGap(12, 12, 12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jArtista)
                                .addComponent(tfArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(3, 3, 3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(jAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDuracao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar)
                        .addComponent(jButton1)
                        .addComponent(btnAlterar)))
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGeneroActionPerformed

    private void tfArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfArtistaActionPerformed

    private void btnTabela(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabela
        // Muda para a aba de tabela
        TabeladeMusicas tabela = new TabeladeMusicas();
        tabela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTabela

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // Cadastra os dados que o usuário inseriu
        String nome = tfNome.getText();
        String artista = tfArtista.getText();
        String album = tfGenero.getText();
        String duracao = tfDuracao.getText();
        
        if(nome.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Preencha o espaço nome");
        }else if(artista.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Preencha o espaço artista");
        }else if(album.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Preencha o espaço album");
        }else if(duracao.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Preencha o espaço duracao");
        }else{
            //Cria o Objeto Usuario
            Musicas musicas = new Musicas(nome, artista, nome, duracao);
            
            //Adiciona Objetos na lista de Obejtos
            listaMusicas.add(musicas);
            
            //exibe mensagem de sucesso
            JOptionPane.showMessageDialog(rootPane, "Sucesso");
            
            //chama o método atualizar tabela
            atualizarTabela();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        try {
            listaMusicas = (ArrayList<Musicas>) Gravador.ler("listaMusicas.dat");
            
            atualizarTabela();
            
            //btnAlterar.setEnabled(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowOpened

    private void TbMusicasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbMusicasMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = TbMusicas.getSelectedRow();
        
        if(linhaSelecionada >= 0){
            btnSalvar.setEnabled(false);//desativa botão
            btnLimpar.setEnabled(false);
            
            //pegar os dadso do usuário e colocar no formulario
            tfNome.setText(listaMusicas.get(linhaSelecionada).getNome());
            tfArtista.setText(listaMusicas.get(linhaSelecionada).getArtista());
            tfGenero.setText(listaMusicas.get(linhaSelecionada).getGenero());
            tfDuracao.setText(listaMusicas.get(linhaSelecionada).getDuracao());
        }
    }//GEN-LAST:event_TbMusicasMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = TbMusicas.getSelectedRow();
        if(linhaSelecionada >= 0){
            String nome = tfNome.getText();
            String artista = tfArtista.getText();
            String album = tfGenero.getText();
            String duracao = tfDuracao.getText();

            if(nome.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Preencha o espaço nome");
            }else if(artista.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Preencha o espaço artista");
            }else if(album.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Preencha o espaço album");
            }else if(duracao.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Preencha o espaço duracao");
            }else{
                //Cria o Objeto Usuario
                Musicas musicas = new Musicas(nome, artista, nome, duracao);

                //Adiciona Objetos na lista de Obejtos
                listaMusicas.remove(linhaSelecionada);
                listaMusicas.add(musicas);

                btnAlterar.setEnabled(false);
                btnSalvar.setEnabled(true);
                btnLimpar.setEnabled(true);

                //exibe mensagem de sucesso
                JOptionPane.showMessageDialog(rootPane, "Sucesso");

                //chama o método atualizar tabela
                atualizarTabela();
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSoundsy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSoundsy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSoundsy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSoundsy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSoundsy().setVisible(true);
            }
        });
    }
        //Método para atualizar tabela
    public void atualizarTabela(){
        
        //Grava a lista de usuarios no arquivo
        try {
            Gravador.gravar("listaMusicas.dat", listaMusicas);
        } catch (Exception e) {
        }
        //Toda vez que o atualizar tabela for chamado irá gravar o array list no arquivo
        
        DefaultTableModel modelo = (DefaultTableModel) TbMusicas.getModel();//Criaçao de um modelo padrão de tabela
        modelo.setNumRows(0);
        
        Object linha[] = new Object[4];//Criação de um vetor de tamanho 6, por causa das colunas
        
        //for para percorrer a lista e atualizar a tabela
        for(int i = 0; i < listaMusicas.size(); i++){
            
            //Cada posição do array é a posição do objeto
            linha[0] = listaMusicas.get(i).getNome();//pega a posição da lista e cadastra o nome do usuario
            linha[1] = listaMusicas.get(i).getArtista();
            linha[2] = listaMusicas.get(i).getGenero();
            linha[3] = listaMusicas.get(i).getDuracao();
            
            modelo.addRow(linha);//adicionar novas linhas
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbMusicas;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jAlbum;
    private javax.swing.JLabel jArtista;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jDuracao;
    private javax.swing.JLabel jNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfArtista;
    private javax.swing.JTextField tfDuracao;
    private javax.swing.JTextField tfGenero;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
